# Это базовая команда. Говорит, что сайт готов, собирать ничего не нужно.
[build]
  publish = "." # Публиковать корень папки

# А это наше ЗОЛОТОЕ правило редиректа.
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200